import React, { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import api from '../../utils/axios';
import { useToast } from '../../context/ToastContext';
import { imageUrl } from '../../utils/format';

const PAGE_SIZE = 10;

const STATUS_FILTERS = [
  ['all', 'All'],
  ['paid', 'Paid'],
  ['pending', 'Pending'],
];

const npr = (x) => `NPR ${Number(x ?? 0).toLocaleString()}`;

// Admin view of every commission record across all agents - flat ledger with
// payment tracking. Commissions themselves are generated by the sale
// verification flow; this page only marks pending ones as paid.
const Commissions = () => {
  const { showToast } = useToast();
  const [searchParams, setSearchParams] = useSearchParams();
  const [commissions, setCommissions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  // Deep-link support: ManageAgents drill-down lands here with ?agent=<id>.
  const [agentFilter, setAgentFilter] = useState(searchParams.get('agent') || '');
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');
  const [sort, setSort] = useState('newest');
  const [page, setPage] = useState(1);
  // Bumped after mutations so the list effect refetches with current filters.
  const [refreshKey, setRefreshKey] = useState(0);
  const [pagination, setPagination] = useState({ page: 1, limit: PAGE_SIZE, total: 0, totalPages: 1 });
  const [totals, setTotals] = useState(null);
  const [agents, setAgents] = useState([]);

  // "Mark as Paid" modal state
  const [payModal, setPayModal] = useState(null); // commission being marked paid
  const [payNote, setPayNote] = useState('');
  const [paying, setPaying] = useState(false);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      setLoading(true);
      setError('');
      try {
        const params = { page, limit: PAGE_SIZE };
        if (statusFilter === 'paid') params.isPaid = 'true';
        if (statusFilter === 'pending') params.isPaid = 'false';
        if (agentFilter) params.agent = agentFilter;
        if (fromDate) params.from = fromDate;
        if (toDate) params.to = toDate;
        params.sort = sort;
        const res = await api.get('/commissions', { params });
        if (cancelled) return;
        setCommissions(res.data?.commissions || []);
        setPagination(res.data?.pagination || { page, limit: PAGE_SIZE, total: 0, totalPages: 1 });
        setTotals(res.data?.totals || null);
      } catch (err) {
        if (cancelled) return;
        setError(err.response?.data?.message || 'Failed to load commissions');
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [statusFilter, agentFilter, fromDate, toDate, page, refreshKey, sort]);

  // Agents for the filter dropdown (admin-only endpoint).
  useEffect(() => {
    let cancelled = false;
    api
      .get('/users', { params: { role: 'agent' } })
      .then((res) => {
        if (!cancelled) setAgents(res.data?.users || []);
      })
      .catch((err) => console.error('Failed to load agents:', err));
    return () => {
      cancelled = true;
    };
  }, []);

  const changeFilter = (setter) => (value) => {
    setter(value);
    setPage(1);
  };

  // Agent dropdown stays synced with the ?agent= URL param so the
  // ManageAgents drill-down (and the X-less back/forward nav) keeps working.
  useEffect(() => {
    const param = searchParams.get('agent') || '';
    setAgentFilter((cur) => (cur === param ? cur : param));
  }, [searchParams]);

  const handleAgentFilterChange = (value) => {
    setAgentFilter(value);
    setPage(1);
    const next = new URLSearchParams(searchParams);
    if (value) next.set('agent', value);
    else next.delete('agent');
    setSearchParams(next, { replace: true });
  };

  const goToPage = (newPage) => {
    if (newPage >= 1 && newPage <= pagination.totalPages) setPage(newPage);
  };

  const openPayModal = (c) => {
    setPayModal(c);
    setPayNote('');
  };

  const confirmMarkPaid = async () => {
    if (!payModal) return;
    setPaying(true);
    try {
      await api.patch(`/commissions/${payModal._id}/mark-paid`, { paidNote: payNote });
      showToast('Commission marked as paid');
      setPayModal(null);
      setRefreshKey((k) => k + 1); // refetch list + totals with current filters
    } catch (err) {
      showToast(err.response?.data?.message || 'Failed to mark as paid', 'error');
    } finally {
      setPaying(false);
    }
  };

  return (
    <div>
      <p className="eyebrow mb-2">Admin</p>
      <h1 className="text-3xl mb-8">Commissions</h1>

      {/* Totals strip - reflects the current filters, not just this page */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6">
        <div className="bg-white border border-navy/10 rounded-sm p-5 shadow-card">
          <p className="text-xs uppercase tracking-wide text-slate-muted mb-2">Paid</p>
          <p className="text-2xl font-display text-sage">
            {totals ? npr(totals.totalPaidAmount) : '—'}{' '}
            <span className="text-sm font-body text-slate-muted">({totals ? totals.paidCount : 0})</span>
          </p>
        </div>
        <div className="bg-white border border-navy/10 rounded-sm p-5 shadow-card">
          <p className="text-xs uppercase tracking-wide text-slate-muted mb-2">Pending</p>
          <p className="text-2xl font-display text-brass-dark">
            {totals ? npr(totals.pendingAmount) : '—'}{' '}
            <span className="text-sm font-body text-slate-muted">({totals ? totals.pendingCount : 0})</span>
          </p>
        </div>
      </div>

      {/* Filters: status chips, agent dropdown, optional date range */}
      <div className="bg-white border border-navy/10 rounded-sm p-4 mb-6 flex flex-wrap items-center gap-3">
        <div className="flex gap-2">
          {STATUS_FILTERS.map(([key, label]) => (
            <button
              key={key}
              onClick={() => changeFilter(setStatusFilter)(key)}
              className={`text-sm px-4 py-2 rounded-sm border ${
                statusFilter === key ? 'bg-navy text-ivory border-navy' : 'border-navy/15 text-navy'
              }`}
            >
              {label}
            </button>
          ))}
        </div>
        <select
          className="input-field sm:w-56"
          value={agentFilter}
          onChange={(e) => handleAgentFilterChange(e.target.value)}
          aria-label="Filter by agent"
        >
          <option value="">All agents</option>
          {/* Keeps the dropdown readable while the agents list is still loading */}
          {agentFilter && !agents.some((a) => a._id === agentFilter) && (
            <option value={agentFilter}>Selected agent</option>
          )}
          {agents.map((a) => (
            <option key={a._id} value={a._id}>
              {a.name}
            </option>
          ))}
        </select>
        <select
          className="input-field sm:w-48"
          value={sort}
          onChange={(e) => changeFilter(setSort)(e.target.value)}
          aria-label="Sort commissions"
        >
          <option value="newest">Newest</option>
          <option value="oldest">Oldest</option>
          <option value="amount_desc">Amount: High→Low</option>
          <option value="amount_asc">Amount: Low→High</option>
        </select>
        <div>
          <label htmlFor="fromDate" className="text-xs text-slate-muted block mb-1">From</label>
          <input
            id="fromDate"
            type="date"
            className="input-field sm:w-40"
            value={fromDate}
            onChange={(e) => changeFilter(setFromDate)(e.target.value)}
          />
        </div>
        <div>
          <label htmlFor="toDate" className="text-xs text-slate-muted block mb-1">To</label>
          <input
            id="toDate"
            type="date"
            className="input-field sm:w-40"
            value={toDate}
            onChange={(e) => changeFilter(setToDate)(e.target.value)}
          />
        </div>
      </div>

      {error && <div className="bg-brick-light text-brick text-sm px-4 py-3 rounded-sm mb-6">{error}</div>}

      {loading ? (
        <p className="text-slate-muted">Loading commissions...</p>
      ) : commissions.length === 0 ? (
        <div className="bg-white border border-navy/10 rounded-sm py-16 text-center">
          <p className="text-slate-muted">No commissions match these filters yet.</p>
        </div>
      ) : (
        <>
          <div className="bg-white border border-navy/10 rounded-sm overflow-x-auto">
            <table className="w-full text-sm min-w-[900px]">
              <thead>
                <tr className="text-left text-xs uppercase tracking-wide text-slate-muted border-b border-navy/10">
                  <th className="px-5 py-3">Property</th>
                  <th className="px-5 py-3">Agent</th>
                  <th className="px-5 py-3">Sale Amount</th>
                  <th className="px-5 py-3">%</th>
                  <th className="px-5 py-3">Commission Amount</th>
                  <th className="px-5 py-3">Status</th>
                  <th className="px-5 py-3">Paid date</th>
                  <th className="px-5 py-3">Action</th>
                </tr>
              </thead>
              <tbody>
                {commissions.map((c) => (
                  <tr key={c._id} className="border-b border-navy/5 last:border-0">
                    <td className="px-5 py-3">
                      <div className="flex items-center gap-3">
                        <img
                          src={imageUrl(c.property?.media?.coverImage)}
                          className="w-10 h-10 rounded-sm object-cover flex-shrink-0"
                          alt={c.property?.title || 'Property'}
                        />
                        {c.property?.slug ? (
                          <Link
                            to={`/properties/${c.property.slug}`}
                            className="font-medium text-navy hover:text-brass"
                          >
                            {c.property?.title || 'Untitled property'}
                          </Link>
                        ) : (
                          <span className="font-medium text-navy">{c.property?.title || 'Untitled property'}</span>
                        )}
                      </div>
                    </td>
                    <td className="px-5 py-3">
                      <p className="text-slate-ink">{c.agent?.name || '—'}</p>
                      {c.agent?.email && <p className="text-xs text-slate-muted">{c.agent.email}</p>}
                    </td>
                    <td className="px-5 py-3 text-slate-ink">{npr(c.saleAmount)}</td>
                    <td className="px-5 py-3 text-slate-ink">{Number(c.commissionPercentage ?? 0)}%</td>
                    <td className="px-5 py-3 font-medium text-navy">{npr(c.commissionAmount)}</td>
                    <td className="px-5 py-3">
                      <span className={`status-badge ${c.isPaid ? 'bg-sage-light text-sage' : 'bg-brass-light text-brass-dark'}`}>
                        {c.isPaid ? 'Paid' : 'Pending'}
                      </span>
                      {c.isPaid && c.paidNote && (
                        <p className="text-xs text-slate-muted mt-1 max-w-[220px]">{c.paidNote}</p>
                      )}
                    </td>
                    <td className="px-5 py-3 text-slate-ink">
                      {c.isPaid && c.paidAt ? new Date(c.paidAt).toLocaleDateString() : '—'}
                    </td>
                    <td className="px-5 py-3">
                      {c.isPaid ? (
                        <span className="text-xs text-slate-muted">—</span>
                      ) : (
                        <button
                          type="button"
                          onClick={() => openPayModal(c)}
                          className="btn-gold text-xs px-3 py-1.5 whitespace-nowrap"
                        >
                          Mark as Paid
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Pagination */}
          <div className="flex items-center justify-between mt-5">
            <p className="text-xs text-slate-muted">
              Showing{' '}
              {pagination.total === 0 ? 0 : (pagination.page - 1) * (pagination.limit || PAGE_SIZE) + 1}–
              {Math.min(pagination.page * (pagination.limit || PAGE_SIZE), pagination.total)} of{' '}
              {pagination.total}
            </p>
            <div className="flex items-center gap-2">
              <button
                onClick={() => goToPage(page - 1)}
                disabled={page <= 1}
                className="text-sm px-3 py-1.5 rounded-sm border border-navy/10 text-slate-muted hover:border-navy/20 disabled:opacity-40 disabled:cursor-not-allowed"
              >
                Previous
              </button>
              <span className="text-sm text-navy px-2">
                {pagination.page} / {pagination.totalPages}
              </span>
              <button
                onClick={() => goToPage(page + 1)}
                disabled={page >= pagination.totalPages}
                className="text-sm px-3 py-1.5 rounded-sm border border-navy/10 text-slate-muted hover:border-navy/20 disabled:opacity-40 disabled:cursor-not-allowed"
              >
                Next
              </button>
            </div>
          </div>
        </>
      )}

      {/* Mark as Paid modal */}
      {payModal && (
        <div
          className="fixed inset-0 z-[200] flex items-center justify-center px-4"
          role="dialog"
          aria-modal="true"
          aria-labelledby="mark-paid-title"
        >
          <div
            className="absolute inset-0 bg-navy-dark/60"
            onClick={() => {
              if (!paying) setPayModal(null);
            }}
          />
          <div className="relative bg-white rounded-sm shadow-lifted max-w-md w-full p-6">
            <h2 id="mark-paid-title" className="font-display text-xl text-navy mb-1">
              Mark commission as paid
            </h2>
            <p className="text-sm text-slate-muted mb-4">
              {npr(payModal.commissionAmount)} — {payModal.property?.title || 'Untitled property'}
            </p>
            <label htmlFor="paidNote" className="label-field">
              Reference note, e.g. cash handed over 2082-05-12
            </label>
            <input
              id="paidNote"
              className="input-field"
              placeholder="Optional"
              value={payNote}
              onChange={(e) => setPayNote(e.target.value)}
              disabled={paying}
            />
            <div className="flex gap-3 justify-end mt-6">
              <button
                type="button"
                onClick={() => setPayModal(null)}
                disabled={paying}
                className="btn-secondary text-sm px-4 py-2"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={confirmMarkPaid}
                disabled={paying}
                className="btn-gold text-sm px-4 py-2 disabled:opacity-60"
              >
                {paying ? 'Saving...' : 'Mark as Paid'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Commissions;
